---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngnix-kishore
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: front-end
          image: ngnix
          ports:
            - containerPort: 80
